//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moxion.CodeAnalysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moxion.CodeAnalysis.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default logging methods like LogInformation, LogWarning, LogError must not be used. Use LogStart, LogCheckPoint, or LogEnd instead..
        /// </summary>
        internal static string MX0001Description {
            get {
                return ResourceManager.GetString("MX0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use &apos;{0}&apos;, use &apos;LogStart&apos;, &apos;LogCheckPoint&apos;, or &apos;LogEnd&apos;.
        /// </summary>
        internal static string MX0001MessageFormat {
            get {
                return ResourceManager.GetString("MX0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Logging Extensions Not Allowed.
        /// </summary>
        internal static string MX0001Title {
            get {
                return ResourceManager.GetString("MX0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule ensures that &apos;LogStart&apos; is used only once in a method to avoid redundant logging at the beginning of method execution. Multiple calls to &apos;LogStart&apos; within the same method could indicate improper logging practices or unnecessary duplication..
        /// </summary>
        internal static string MX0002Description {
            get {
                return ResourceManager.GetString("MX0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;LogStart&apos; method should appear at most once in a method.
        /// </summary>
        internal static string MX0002MessageFormat {
            get {
                return ResourceManager.GetString("MX0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple LogStart Calls Not Allowed.
        /// </summary>
        internal static string MX0002Title {
            get {
                return ResourceManager.GetString("MX0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;LogStart&apos; must have exactly one &apos;LogEnd&apos; call within the same method. Ensure that &apos;LogEnd&apos; is called before any &apos;return&apos; statements to maintain proper logging flow..
        /// </summary>
        internal static string MX0003Description {
            get {
                return ResourceManager.GetString("MX0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;LogStart&apos; must be paired with a corresponding &apos;LogEnd&apos;.
        /// </summary>
        internal static string MX0003MessageFormat {
            get {
                return ResourceManager.GetString("MX0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogStart must be paired with LogEnd.
        /// </summary>
        internal static string MX0003Title {
            get {
                return ResourceManager.GetString("MX0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensures that LogStart is called before LogEnd in the same method..
        /// </summary>
        internal static string MX0004Description {
            get {
                return ResourceManager.GetString("MX0004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogStart must be invoked before LogEnd.
        /// </summary>
        internal static string MX0004MessageFormat {
            get {
                return ResourceManager.GetString("MX0004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogStart must appear before LogEnd.
        /// </summary>
        internal static string MX0004Title {
            get {
                return ResourceManager.GetString("MX0004Title", resourceCulture);
            }
        }
    }
}
