<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Moxion.Presentation"/>
        <InternalsVisibleTo Include="Moxion.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Moxion.CodeAnalysis\Moxion.CodeAnalysis.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Moxion.Application\Moxion.Application.csproj" />
        <ProjectReference Include="..\Moxion\Moxion.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="12.4.1"/>
    </ItemGroup>

</Project>
