<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Moxion.CodeAnalysis\Moxion.CodeAnalysis\Moxion.CodeAnalysis.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" Version="8.1.0"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11"/>
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0"/>
        <PackageReference Include="Serilog.AspNetCore.Plus" Version="8.0.0"/>
        <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
        <Content Update="wwwroot\swagger\SwaggerDark.css">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <None Include="ClientApp\package.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </None>
        <None Include="ClientApp\package-lock.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </None>
        <None Include="ClientApp\tsconfig.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </None>
        <None Include="ClientApp\tsconfig.app.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </None>
        <None Include="ClientApp\tsconfig.node.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Moxion.Presentation\Moxion.Presentation.csproj"/>
    </ItemGroup>

</Project>
