<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture" Version="4.18.1" />
        <PackageReference Include="AutoFixture.AutoNSubstitute" Version="4.18.1" />
        <PackageReference Include="AutoFixture.Xunit2" Version="4.18.1" />
        <PackageReference Include="coverlet.collector" Version="6.0.0"/>
        <PackageReference Include="FluentAssertions" Version="8.0.0" />
        <PackageReference Include="FluentAssertions.Analyzers" Version="0.34.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="1.1.2" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing" Version="1.1.2" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeRefactoring.Testing" Version="1.1.2" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing" Version="1.1.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0"/>
        <PackageReference Include="NSubstitute" Version="5.3.0" />
        <PackageReference Include="xunit" Version="2.5.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Moxion.Application\Moxion.Application.csproj" />
      <ProjectReference Include="..\Moxion.CodeAnalysis\Moxion.CodeAnalysis.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="CodeAnalysis\CodeFixes\" />
      <Folder Include="CodeAnalysis\CodeRefactors\" />
      <Folder Include="CodeAnalysis\Syntaxes\" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="xunit.runner.json">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
    </ItemGroup>

</Project>
